# Generated by Django 5.2.5 on 2025-08-20 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_paciente_acudiente_paciente_correo_electronico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.paciente'),
            preserve_default=False,
        ),
    ]
